### ISSUE TITLE
Add more features to this project

### ISSUE THREAD

**Issue by mastergberry** [UCSB-CS56-Projects/cs56-utilities-rss-reader#8]
~depends https://github.com/UCSB-CS56-Projects/cs56-utilities-rss-reader/issues/6

There are a bunch of extra features available on https://www.commafeed.com/api/ Go ahead and add some of these extra features to the project to make it more complete.  It appears at the moment all it does is basic authentication.

~Estimated 100 points per feature added w/ JUnit tests
~Estimated 50 points per GUI piece adder per feature

This means you can earn 150 points per feature you add from their API if you create a GUI for the feature you add.

**Comment by steve-fields** [comment]
F16 CLOSED: too vague
